import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { cookies } from "next/headers";
import { UserProvider } from "./userContext";
import { jwtDecode } from "jwt-decode";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let userId = ""
  const refreshToken = cookies().get("session_refresh_token")?.value
  if (refreshToken) {userId = jwtDecode(refreshToken).user_id};

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>

        <UserProvider userId={userId}>{children}</UserProvider>
        
      </body>
    </html>
  );
}
