# Generated by Django 5.2.4 on 2025-08-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_job_skills_job_requirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='position_salary',
            new_name='salary',
        ),
    ]
