# Generated by Django 5.2.4 on 2025-08-15 16:57

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_position_salary_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=job.models.default_deadline),
        ),
    ]
