# Generated by Django 5.2.4 on 2025-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], max_length=50),
        ),
    ]
