import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "@/components/Navbar";
import { jwtDecode } from "jwt-decode";
import { MyJwtPayload } from "@/types";
import { cookies } from "next/headers";
import { UserProvider } from "./userContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Let's Work",
  description: "Generated by create next app",
};


  



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  let user_id = "";
  let is_recruiter = false;

  const refreshToken = (await cookies()).get("session_refresh_token")?.value
  
  if (refreshToken) {
    user_id = jwtDecode<MyJwtPayload>(refreshToken).user_id
    is_recruiter = jwtDecode<MyJwtPayload>(refreshToken).is_recruiter
  };



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <UserProvider userInfo ={{ user_id, is_recruiter }}>
        <Navbar key={user_id} />      
        {children}
      </UserProvider>
        
        <Toaster position="top-right" richColors />

      </body>
    </html>
  );
}
