# Generated by Django 5.2.4 on 2025-08-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_cv_user_desired_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='years_of_experience',
            new_name='experience',
        ),
    ]
