# Generated by Django 5.2.4 on 2025-08-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_years_of_experience_user_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
